# Generated by Django 5.1.15 on 2026-09-18 06:46

import apps.armory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="sword", max_length=50)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common"),
                            ("RARE", "Rare"),
                            ("EPIC", "Epic"),
                            ("LEGENDARY", "Legendary"),
                            ("MYTHIC", "Mythic"),
                            ("ANCIENT", "Ancient"),
                        ],
                        db_index=True,
                        default="RARE",
                        max_length=20,
                    ),
                ),
                ("fictional_power_rating", models.IntegerField(default=85)),
                ("fictional_stability", models.IntegerField(default=90)),
                (
                    "energy_type",
                    models.CharField(default="Plasma Quantum Core", max_length=100),
                ),
                (
                    "primary_material",
                    models.CharField(
                        default="Hyper-Dense Mithril Alloy", max_length=100
                    ),
                ),
                (
                    "size_class",
                    models.CharField(default="Medium Dual-Hand", max_length=50),
                ),
                ("description", models.TextField()),
                ("lore_snippet", models.TextField(blank=True, default="")),
                (
                    "fictional_manufacturer",
                    models.CharField(default="Voidstar Foundry", max_length=150),
                ),
                (
                    "fictional_creation_era",
                    models.CharField(default="3rd Astral Epoch", max_length=100),
                ),
                ("image_url", models.URLField(blank=True, default="")),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weapons",
                        to="armory.category",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weapons",
                        to="universes.faction",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapons",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "ordering": ["-fictional_power_rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeaponAnimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Idle Showcase", max_length=100)),
                (
                    "animation_type",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle Rotation"),
                            ("ENERGY", "Energy Activation"),
                            ("TRANSFORM", "Core Transformation"),
                            ("SHOWCASE", "Cinematic Sweep"),
                        ],
                        default="IDLE",
                        max_length=50,
                    ),
                ),
                ("duration", models.FloatField(default=4.0)),
                ("particle_surge", models.BooleanField(default=True)),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animations",
                        to="armory.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeaponModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "glb_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.armory.models.weapon_glb_upload_path,
                    ),
                ),
                (
                    "procedural_type",
                    models.CharField(
                        default="crystal_blade",
                        help_text="Fallback 3D procedural shape type: crystal_blade, plasma_rifle, void_staff, sci_scythe, hyper_shield, cosmic_cannon",
                        max_length=50,
                    ),
                ),
                ("primary_color", models.CharField(default="#00f0ff", max_length=20)),
                ("secondary_color", models.CharField(default="#ff007f", max_length=20)),
                ("glow_intensity", models.FloatField(default=1.5)),
                ("default_scale", models.FloatField(default=1.0)),
                ("rotation_speed", models.FloatField(default=0.005)),
                (
                    "weapon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_3d",
                        to="armory.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeaponVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_name", models.CharField(max_length=150)),
                ("color_theme", models.CharField(default="#ff0000", max_length=30)),
                ("power_modifier", models.IntegerField(default=5)),
                ("lore_note", models.TextField(blank=True, default="")),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="armory.weapon",
                    ),
                ),
            ],
        ),
    ]
