version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: armory_postgres
    environment:
      POSTGRES_DB: armory_db
      POSTGRES_USER: armory_user
      POSTGRES_PASSWORD: armory_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: armory_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    container_name: armory_backend
    command: sh -c "python manage.py migrate && python seed_armory.py && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-3d-armory-production-key
      - DJANGO_SETTINGS_MODULE=config.settings.development
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    container_name: armory_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
