# Generated by Django 5.1.15 on 2026-09-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Novice Collector", max_length=100)),
                ("level", models.IntegerField(default=1)),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "performance_mode",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Quality (Full Shaders & Particles)"),
                            ("MEDIUM", "Medium Quality (Standard WebGL)"),
                            ("LOW", "Low Quality (Performance Mode)"),
                        ],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                ("sound_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
