# Generated by Django 5.1.15 on 2026-09-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("armory", "0001_initial"),
        ("universes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("origin_story", models.TextField()),
                ("historical_events", models.TextField()),
                ("legendary_bearers", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="universes.location",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lore_entries",
                        to="armory.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_year",
                    models.CharField(default="Year 1400 AE", max_length=100),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "featured_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="universes.character",
                    ),
                ),
                (
                    "featured_weapon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="armory.weapon",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "ordering": ["event_year"],
            },
        ),
    ]
