# Generated by Django 5.1.15 on 2026-09-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "allegiance",
                    models.CharField(default="Neutral Alliance", max_length=100),
                ),
                ("symbol_icon", models.CharField(default="shield", max_length=100)),
                ("color_theme", models.CharField(default="#00f0ff", max_length=30)),
                ("description", models.TextField()),
                (
                    "headquarters",
                    models.CharField(default="Unknown Citadel", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField()),
                ("era", models.CharField(default="Ethereal Age", max_length=100)),
                ("banner_image", models.URLField(blank=True, default="")),
                ("status", models.CharField(default="Active Realm", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("title", models.CharField(default="Warlord", max_length=150)),
                ("status", models.CharField(default="Legendary", max_length=50)),
                ("lore", models.TextField()),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="universes.faction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "sector_type",
                    models.CharField(default="Ancient Ruins", max_length=100),
                ),
                ("map_coordinates_x", models.FloatField(default=0.0)),
                ("map_coordinates_y", models.FloatField(default=0.0)),
                ("map_coordinates_z", models.FloatField(default=0.0)),
                ("description", models.TextField()),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="universes.universe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="faction",
            name="universe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factions",
                to="universes.universe",
            ),
        ),
    ]
